"""empty message

Revision ID: 154176cf5442
Revises: 141b6eb211d9
Create Date: 2020-01-16 22:22:02.216830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154176cf5442'
down_revision = '141b6eb211d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('date_approved', sa.DateTime(), nullable=True))
    op.add_column('company', sa.Column('date_requested', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'date_requested')
    op.drop_column('company', 'date_approved')
    # ### end Alembic commands ###
