"""empty message

Revision ID: 28fa1521692f
Revises: de8bfb29afa6
Create Date: 2020-01-28 20:31:51.604656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28fa1521692f'
down_revision = 'de8bfb29afa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date_purchased', sa.DateTime(), nullable=True))
    op.drop_column('orders', 'date_puchased')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date_puchased', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'date_purchased')
    # ### end Alembic commands ###
