"""added company description

Revision ID: 454f3421c279
Revises: 5838b0393676
Create Date: 2020-01-20 21:17:27.604815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454f3421c279'
down_revision = '5838b0393676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'description')
    # ### end Alembic commands ###
