"""added cover pic

Revision ID: 6e2809ad6e72
Revises: 154176cf5442
Create Date: 2020-01-19 23:06:20.371211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2809ad6e72'
down_revision = '154176cf5442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('cover_pic', sa.String(length=1000), nullable=True))
    op.drop_constraint('company_email_key', 'company', type_='unique')
    op.add_column('user', sa.Column('profile_pic', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_pic')
    op.create_unique_constraint('company_email_key', 'company', ['email'])
    op.drop_column('company', 'cover_pic')
    # ### end Alembic commands ###
