"""empty message

Revision ID: 9d17daf6ebad
Revises: f71155d1d44f
Create Date: 2020-03-17 19:52:03.136557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d17daf6ebad'
down_revision = 'f71155d1d44f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('from_address', sa.String(length=200), nullable=True),
    sa.Column('to_address', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('date_requested', sa.DateTime(), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'address')
    op.drop_table('task_requests')
    # ### end Alembic commands ###
