"""added fooditem model

Revision ID: a8a9358db945
Revises: e7fdc59e3084
Create Date: 2020-01-21 23:54:47.242791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a9358db945'
down_revision = 'e7fdc59e3084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('cover_pic', sa.String(length=1000), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('food_item_hash', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_item')
    # ### end Alembic commands ###
