"""added hash in company

Revision ID: c93d19588882
Revises: 6e2809ad6e72
Create Date: 2020-01-20 00:12:27.358887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93d19588882'
down_revision = '6e2809ad6e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'company_hash')
    # ### end Alembic commands ###
