"""added social id

Revision ID: d597a567d587
Revises: 99cc38ec709a
Create Date: 2020-01-13 19:32:32.972933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd597a567d587'
down_revision = '99cc38ec709a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('social_id', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'user', ['social_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'social_id')
    # ### end Alembic commands ###
