"""empty message

Revision ID: ead123799706
Revises: 454f3421c279
Create Date: 2020-01-20 21:55:44.769509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ead123799706'
down_revision = '454f3421c279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submenu', 'description')
    # ### end Alembic commands ###
