"""empty message

Revision ID: 2856153b5861
Revises: 
Create Date: 2020-06-18 01:03:39.036070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2856153b5861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('from_address', sa.String(length=200), nullable=True),
    sa.Column('to_address', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('date_requested', sa.DateTime(), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('admins', sa.Column('admin', sa.Integer(), nullable=True))
    op.drop_constraint('admins_user_fkey', 'admins', type_='foreignkey')
    op.create_foreign_key(None, 'admins', 'user', ['admin'], ['id'])
    op.drop_column('admins', 'user')
    op.add_column('staffs', sa.Column('staff', sa.Integer(), nullable=True))
    op.drop_constraint('staffs_user_fkey', 'staffs', type_='foreignkey')
    op.create_foreign_key(None, 'staffs', 'user', ['staff'], ['id'])
    op.drop_column('staffs', 'user')
    op.add_column('user', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'address')
    op.add_column('staffs', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'staffs', type_='foreignkey')
    op.create_foreign_key('staffs_user_fkey', 'staffs', 'user', ['user'], ['id'])
    op.drop_column('staffs', 'staff')
    op.add_column('admins', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.create_foreign_key('admins_user_fkey', 'admins', 'user', ['user'], ['id'])
    op.drop_column('admins', 'admin')
    op.drop_table('task_requests')
    # ### end Alembic commands ###
