"""changed checkout model to orders

Revision ID: 922be568e810
Revises: 086861e08a5c
Create Date: 2020-01-28 00:28:44.962564

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '922be568e810'
down_revision = '086861e08a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_item_hash', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.String(length=16), nullable=True),
    sa.Column('date_puchased', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('checkout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkout',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('food_item_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.Column('date_puchased', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='checkout_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='checkout_pkey')
    )
    op.drop_table('orders')
    # ### end Alembic commands ###
