"""empty message

Revision ID: de8bfb29afa6
Revises: 922be568e810
Create Date: 2020-01-28 00:33:41.994195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8bfb29afa6'
down_revision = '922be568e810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('food_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'food_item', ['food_item_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'food_item_id')
    # ### end Alembic commands ###
