"""empty message

Revision ID: e77bbb075269
Revises: 91e7b8d16b35
Create Date: 2020-03-03 16:18:34.081029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77bbb075269'
down_revision = '91e7b8d16b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    op.drop_index('ix_user_username', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
