"""added submenu hash

Revision ID: e7fdc59e3084
Revises: ead123799706
Create Date: 2020-01-21 00:33:11.552093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fdc59e3084'
down_revision = 'ead123799706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submenu', sa.Column('submenu_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submenu', 'submenu_hash')
    # ### end Alembic commands ###
